name: pull-request-opened

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  pull-request-open:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Show message
        run: |
          echo "PR Num: ${{ github.event.pull_request.number }}"
          echo "URL: ${{ github.event.pull_request.url }}"

          echo "user.login: ${{ github.event.pull_request.user.login }}"
          echo "user.id: ${{ github.event.pull_request.user.id }}"
          echo "user.site_admin: ${{ github.event.pull_request.user.site_admin }}"

          echo "base.ref: ${{ github.event.pull_request.base.ref }}"
          echo "base.repo.fork: ${{ github.event.pull_request.base.repo.fork }}"

          echo "head.ref: ${{ github.event.pull_request.head.ref }}"
          echo "head.repo.fork: ${{ github.event.pull_request.head.repo.fork }}"

      - name: Run cmd
        run: env

